<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-KJ4U1G6" name="org.br.auto_pom.auto_pom.HomePageTest" tests="7" failures="2" timestamp="04 Jan 2020 05:01:57 GMT" time="13.155" errors="0">
  <testcase name="checkTitle" time="0.030" classname="org.br.auto_pom.auto_pom.HomePageTest"/>
  <testcase name="checkPopUp" time="3.681" classname="org.br.auto_pom.auto_pom.HomePageTest"/>
  <testcase name="checkLogos" time="0.699" classname="org.br.auto_pom.auto_pom.HomePageTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	logos mismatch expected [Old] but found [Old Navy],
	logos mismatch expected [Hill] but found [Hill City]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
logos mismatch expected [Old] but found [Old Navy],
logos mismatch expected [Hill] but found [Hill City]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at org.br.auto_pom.auto_pom.HomePageTest.checkLogos(HomePageTest.java:78)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkLogos -->
  <testcase name="checkNavBarMenu" time="2.394" classname="org.br.auto_pom.auto_pom.HomePageTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	nav bar mismatch expected [GIFTS] but found [ABOUT US]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
nav bar mismatch expected [GIFTS] but found [ABOUT US]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at org.br.auto_pom.auto_pom.HomePageTest.checkNavBarMenu(HomePageTest.java:114)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkNavBarMenu -->
  <testcase name="checkShopBag" time="0.062" classname="org.br.auto_pom.auto_pom.HomePageTest"/>
  <testcase name="checkSignIn" time="0.345" classname="org.br.auto_pom.auto_pom.HomePageTest"/>
  <testcase name="clickSignIn" time="5.944" classname="org.br.auto_pom.auto_pom.HomePageTest"/>
</testsuite> <!-- org.br.auto_pom.auto_pom.HomePageTest -->
